baseURL = "https://parity.uk"
languageCode = "en-gb"
title = "Parity Network"
archive-paginate = 10
[taxonomies]
  category = "categories"

[menus]
  [[menus.main]]
    name = "About us"
    url = "/about-us/"
    weight = 1
  [[menus.main]]
    name = "How it works"
    url = "/how-it-works/"
    weight = 2
  [[menus.main]]
    name = "Pricing"
    url = "/pricing/"
    weight = 3
  [[menus.main]]
    name = "Blog"
    url = "/posts/"
    weight = 4
  [[menus.main]]
    name = "FAQs"
    url = "/faqs/"
    weight = 5
  [[menus.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6


[outputFormats]
  [outputFormats.AppFormat]
    name = "app"
    isPlainText = false
    mediaType = "text/html"
    isHTML = true
    permalinkable = true
    path = "app"

[outputs]
  section = ["HTML", "APP", "AMP"]
  page = ["HTML", "APP", "AMP"]