baseURL = "https://parity.uk"
languageCode = "en-gb"
title = "Parity Network"
[markup.goldmark.renderer]
  unsafe= true
[params]
  archive-paginate = 10
  marketplace_categories = ["Business Services", "Business Tools", "Premises & Office", "Food & Beverage"]

[taxonomies]
  category = "categories"

[menus]
  [[menus.main]]
    name = "Marketplace"
    url = "/marketplace"
    weight = 1
  [[menus.main]]
    name = "How it Works"
    url = "/how-it-works/"
    weight = 2
  [[menus.main]]
    name = "Pricing"
    url = "/pricing/"
    weight = 3
  [[menus.main]]
    name = "FAQs"
    url = "/faqs/"
    weight = 4
  [[menus.main]]
    name = "Blog"
    url = "/posts/"
    weight = 5
  [[menus.main]]
    name = "About Us"
    url = "/about-us/"
    weight = 6
  [[menus.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

[outputFormats]
  [outputFormats.AppFormat]
    name = "app"
    isPlainText = false
    mediaType = "text/html"
    isHTML = true
    permalinkable = true
    path = "app"

[outputs]
  section = ["HTML", "APP", "JSON"]
  page = ["HTML", "APP", "JSON"]